################################################################
## Packages / Blue Iris
################################################################
camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.1.20:81/mjpg/FrontDoor  # This needs to be the URL of your Blue Iris server
    name: Front Door 
    # If you've configured the BI Web Server to not require authentication from
    # LAN connections, remove the the following three lines
    username: !secret bi_username
    password: !secret bi_password
    authentication: basic

binary_sensor:
  - platform: template
    sensors:
      front_door_motion:
        device_class: motion
        value_template: "{{ is_state('input_boolean.front_door_motion', 'on') }}"

input_boolean:
  front_door_motion:
    name: Front Door Motion
